# Generated by Django 4.2.1 on 2023-05-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_programador_actividad_remove_programador_edad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programador',
            name='alta',
            field=models.CharField(default="<attribute 'day' of 'datetime.date' objects>/<attribute 'month' of 'datetime.date' objects>/<attribute 'year' of 'datetime.date' objects>", max_length=20),
        ),
        migrations.AlterField(
            model_name='programador',
            name='ingreso',
            field=models.CharField(default="<attribute 'day' of 'datetime.date' objects>/<attribute 'month' of 'datetime.date' objects>/<attribute 'year' of 'datetime.date' objects>", max_length=20),
        ),
    ]
